README.md, library/build.gradle, library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/builder/HlsRenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/builder/RenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/event/EMMediaProgressEvent.java, library/src/main/java/com/devbrackets/android/exomedia/exoplayer/EMExoPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/listener/InfoListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/InternalErrorListener.java, library/src/main/java/com/devbrackets/android/exomedia/util/MediaUtil.java
Updated the ExoPlayer version
Updated the Library version
=> Exoplayer update

library/build.gradle, library/src/main/java/com/devbrackets/android/exomedia/EMNotification.java, library/src/main/java/com/devbrackets/android/exomedia/service/EMPlaylistService.java, library/src/main/res/layout-v16/exomedia_big_notification_content.xml, library/src/main/res/layout/exomedia_notification_content.xml, library/src/main/res/values-v21/dimen.xml, library/src/main/res/values/dimen.xml
Added a custom small (standard) notification to allow for media playback controls.
Fixed an issue with the EMPlaylistService where the notification images weren't being updated correctly
=> Custom small notification & notification image fixes

library/src/main/java/com/devbrackets/android/exomedia/EMListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java
Fixed an issue where the preview image on the EMVideoView would hide when playback was ready instead of when playback started.
=> Fixed Preview Image

library/src/main/java/com/devbrackets/android/exomedia/builder/HlsRenderBuilder.java
(actual commit should be use 'AsyncRendererBuilder' in HLS RenderBuilder)
So that it matches the other RenderBuilder implementations. Which is cleaner imo.
=> Make RenderBuilder for HLS async

library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/builder/DashRenderBuilder.java
Only added to the VideoView implementation, this should also be usable for the AudioPlayer.
But I only have good test videostreams.
=> Add RenderBuilder for DASH support

library/src/main/java/com/devbrackets/android/exomedia/builder/DashRenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/builder/HlsRenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/builder/RenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/builder/SmoothStreamRenderBuilder.java
Give the users of the library the ability to specify the audio stream type instead of just defaulting to STREAM_MUSIC.
=> Allow specification of audio stream type.

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java
Updated VideoViewApi implementation retrieval to allow for easier reading and explicit documentation.
Updated private methods and variables in the EMVideoView to be protected for fully supporting extension
=> Updated Documentation

library/src/main/java/com/devbrackets/android/exomedia/EMLockScreen.java, library/src/main/java/com/devbrackets/android/exomedia/EMNotification.java, library/src/main/java/com/devbrackets/android/exomedia/service/EMPlaylistService.java
Added null checks, minor helper cleanup to avoid null cases
=> Fixed Issue #110

demo/src/main/java/com/devbrackets/android/exomediademo/playlist/AudioApi.java, demo/src/main/java/com/devbrackets/android/exomediademo/playlist/BaseMediaApi.java, demo/src/main/java/com/devbrackets/android/exomediademo/playlist/VideoApi.java, demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/FullScreenVideoPlayerActivity.java, demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/VideoPlayerActivity.java, library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/EMListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/NativeVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/TextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/listener/OnBufferUpdateListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/OnCompletionListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/OnErrorListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/OnPreparedListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/OnSeekCompletionListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/VideoControlsListener.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java
Updated the  listener interfaces to use custom ones instead of the MediaPlayer ones
Fixed the Demo to use the new listener interfaces with the PlaylistCore playlist support
=> Custom Listener interfaces instead of the MediaPlayer ones

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java
Updated the EMVideoView to correctly keep the screen on when playing a video
=> Updated the EMVideoView to use setKeepScreenOn()

library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/EMListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java
-  Minor cleanup around the MuxNotifier and MuxListener
=> Listener mux cleanup

demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/FullScreenVideoPlayerActivity.java, library/src/main/java/com/devbrackets/android/exomedia/listener/VideoControlsButtonListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/VideoControlsSeekListener.java, library/src/main/java/com/devbrackets/android/exomedia/listener/VideoControlsVisibilityListener.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java
-  How Progress Polling is performed from the `VideoControls`
- Cleaned up the `VideoControls` listeners
- Standardized the `VideoControls` listener interaction with default functionality
=> Video controls architecture

demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/AudioPlayerActivity.java, library/src/main/java/com/devbrackets/android/exomedia/core/EMListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/listener/ExoPlayerListener.java
-  adds a seek complete listener to the ExoPlayer
=> ExoPlayer onSeekComplete

library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/annotation/TrackRenderType.java, library/src/main/java/com/devbrackets/android/exomedia/core/EMListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/MediaPlayerApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/NativeVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java
-  Adds the ability to retrieve available tracks for each media channel type (render type)
- Adds the ability to switch to a specified track
=> Added track selection

library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java
-  A `ViewTreeObserver` leak in `ResizingTextureView` is fixed
=> Fix a ViewTreeObserverLeak

build.gradle
=> Update android plugin to 2.0

demo/src/main/java/com/devbrackets/android/exomediademo/service/MediaService.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java, library/src/main/res/layout/exomedia_default_controls_mobile.xml
-  Updates the `VideoControls` to hide the text container (title, subtitle, description) if no text is specified
=> Hide video controls text

library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/MediaPlayerApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeMediaPlayer.java
- Updated the EMAudioPlayer to correctly use a seekTo time specified before the media is prepared
=> Fixed #201 (SeekTo before prepared)

library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/type/MediaSourceType.java, library/src/main/java/com/devbrackets/android/exomedia/util/MediaSourceUtil.java
- Updated the media source type determination (for ExoPlayer backed implementations) to use a more ruggedized comparison
=> Fixes #143

demo/src/main/res/layout/video_player_activity.xml, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/NativeVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java, library/src/main/res/layout/exomedia_video_view_layout.xml
- Removed the EMVideoView shutters as they are no longer necessary
=> Fixes #171 (shutter sizing issues)

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java
- Removed the swapping of width and height for the intrinsic  video size
=> Fixes #212 scaling issues

library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/TextureVideoView.java
- Fixes a crash due to using an incorrect surface reference when clearing the surface
=> Fixes Issue #224

library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/EMListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/MediaPlayerApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/builder/DashRenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/builder/HlsRenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/builder/RenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/builder/SmoothStreamRenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ClearableSurface.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingSurfaceView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/util/DrmProvider.java
- Adds callbacks and interfaces for supporting DRM (API 18 +)
=> Fixes Issue 243

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java
- Fixes the `getAvailableTracks()` method to use the correct track count
=> Fixes issue #296, incorrect available track count

demo/build.gradle, demo/src/main/java/com/devbrackets/android/exomediademo/App.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java
- Fixes a memory leak in the `VideoControls`
=> [#306] Fixed a memory leak in the VideoControls

build.gradle, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java
- Fixes a memory leak in the `EMExoPlayer` listeners
=> Fixes #301 (Memory Leak)

demo/src/main/res/layout/audio_player_activity.xml, library/build.gradle, library/src/main/java/com/devbrackets/android/exomedia/util/EMResourceUtil.java, library/src/main/res/layout/exomedia_default_controls_mobile.xml
- Updated the default controls to use support vector drawables instead of the png generation
=> Fixes #270

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java
- Adds methods to set drawables for the `VideoControls`
=> Fixes issue #314

library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/EMListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/builder/RenderBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java
- Adds Buffer listener support to the `EMExoPlayer`
- Adds a proper `Id3MetadataListener` path
=> Fixed issue 263 where the EMExoPlayer wouldn't report buffer changes

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java
- Added audio focus handling to the EMVideoView
=> [#280] Adds AudioFocus handling to the EMVideoView

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java
=> Fix reversed code in methods onRewindClicked / onFastForwardClicked

library/build.gradle, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java
- [ V] This pull request follows the coding standards
- EMExoPlayer.replaceRenderBuilder method to unregister existing audioCapabilitiesReceiver before registering new one
=> #353 potential fix

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java
EMVideoView now respects attributes videoViewApiImpl and videoViewApiImplLegacy appropriately.
=> EMVideoView now respects attributes videoViewApiImpl and videoViewApiImplLegacy appropriately.

demo/src/main/java/com/devbrackets/android/exomediademo/playlist/AudioApi.java, library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/MediaPlayerApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/listener/InternalErrorListener.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/listener/VideoControlsSeekListener.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Updates the position and duration methods and callbacks to use `long` instead of `int`
=> Addresses Issue 327

demo/src/main/java/com/devbrackets/android/exomediademo/playlist/BaseMediaApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/ListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/exception/NativeMediaPlaybackException.java, library/src/main/java/com/devbrackets/android/exomedia/listener/OnErrorListener.java
- Added exceptional information to the `OnErrorListener`
=> Addresses #299, Added error information to the OnErrorListener

demo/build.gradle, demo/src/main/java/com/devbrackets/android/exomediademo/App.java, library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/MediaSourceBuilder.java
- Added an way to provide the default data source to use for media sources
=> Fixes #86, API for overriding HttpDataSource

library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingSurfaceView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java, library/src/main/res/values/attributes.xml
- Updates the VideoView backing to default to SurfaceView instead of TextureView
- Fixed scaling issues in the SurfaceView
=> Fixes Issue #371

library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/listener/OnVideoSizeChangedListener.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Added a callback for video size changes
- Adds missing `@Nullable` annotations
=> Addresses #418: Video size change listener

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java
- Fixed a state issue that caused the seek completion listener to not always be informed
=> Fixes Issue #423

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
=> Fix LeakCanary warnings about AudioManager leaks

demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/FullScreenVideoPlayerActivity.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Updated he Demo FullscreenVIdeoPlayerActivity to correctly setup the UI flags
- Added the ability to specify the hide delay for the VideoControls
=> [#436] Adds VideoControls setHideDelay() method 

demo/src/main/java/com/devbrackets/android/exomediademo/service/MediaService.java
Just replaced "Picasso" with "Glide"
-
=> [Comment Cleanup] Comments mention "Picasso Image Loader Class"

demo/build.gradle, library/build.gradle, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java
- Updates ExoPlayer to `2.5.1`
- Updates AppCompat to `26.0.0`
=> Updated dependency versions

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Updated the VideoView's audio focus to handle transient losses more appropriately
=> [#505] Transient audio focus updates

build.gradle, demo/src/main/java/com/devbrackets/android/exomediademo/adapter/SampleListAdapter.java, demo/src/main/java/com/devbrackets/android/exomediademo/adapter/StartupListAdapter.java, demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/AudioPlayerActivity.java, demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/StartupActivity.java, library/src/main/java/com/devbrackets/android/exomedia/core/ListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/listener/InternalErrorListener.java, library/src/main/java/com/devbrackets/android/exomedia/core/renderer/RendererProvider.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/MediaSourceProvider.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/FitsSystemWindowRelativeLayout.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
-  Cleaned up from the support library 27.0.0 update
=> [#533] Updated to ExoPlayer 2.6.0

build.gradle, demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/VideoSelectionActivity.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java
- ExoPlayer version updated to `2.6.1` (from `2.6.0`
- Fixed an incorrect track index calculation in the `ExoMediaPlayer`
=> Fixed an issue (#541) where incorrect track indexes were being used

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java
This PR fixes some javadoc issues, which caused the build on Jitpack to [fail](https://jitpack.io/com/github/brianwernick/ExoMedia/master-4.1.0-g9f151d9-5/build.log).
=> Fix javadoc issues

library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/AudioPlayerApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Added the ability to specify the repeat mode to the `VideoView` and `AudioPlayer`
=> Adds Repeat Mode

library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/AudioPlayerApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Added methods to get the current audio volume
=> Added the ability to get the current volume of the media

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java
This allows analytics to be added to the ExoPlayer (Example Youbora).
=> Add getter to ExoMediaPlayer for the ExoPlayer

build.gradle, library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/AudioPlayerApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Updated the track selection to include the group index
=> [#616] Fixes track selection

demo/src/main/java/com/devbrackets/android/exomediademo/playlist/AudioApi.java, demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/VideoPlayerActivity.java, library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/ListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
Add support for AnalyticsCollector and AnalyticsListener
Added AnalyticsListener to the ListenerMux
=> AnalyticsCollector

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java
- Added a `getSelectedTrackIndex` method that takes the `groupIndex`, deprecating the original that assumes group 0
=> Selected Track Group Index

build.gradle, demo/build.gradle, demo/src/main/java/com/devbrackets/android/exomediademo/App.java, library/build.gradle, library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java, library/src/main/java/com/devbrackets/android/exomedia/core/ListenerMux.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/MediaSourceProvider.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/DashMediaSourceBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/DefaultMediaSourceBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/HlsMediaSourceBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/MediaSourceBuilder.java, library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/SsMediaSourceBuilder.java
=> Updated the ExoPlayer to 2.9.0

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java
If different audio renderers extensions connected to the ExoPlayer (ffmpeg extension, for example) and the video file contains audio tracks of different types handled by different renderers (for example aac and ac-3) there will be multiple renderer tracks in the MappedTrackInfo. Only one renderer of the same type may work properly at the time, so if selecting track in one renderer another renderer should be disabled to avoid playback errors.
This commits tries to handle multiple renderers automatically in the transparent way. Resulting API is untouched so it should be possible to work with multiple renderers of the same type in the same way as with a single renderer.
=> Add support of multiple renderers of the same type

build.gradle, demo/build.gradle, gradle/wrapper/gradle-wrapper.properties, library/build.gradle, library/gradle/publish.gradle
- Updated the library publication to use the bintray plugin directly instead of the novoda wrapper
=> Migration from Novoda bintray-release to the bintray plugin

demo/build.gradle, demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/VideoPlayerActivity.java, demo/src/main/java/com/devbrackets/android/exomediademo/ui/subtitle/AspectRatioFrameLayout.kt, demo/src/main/java/com/devbrackets/android/exomediademo/ui/subtitle/SubtitlePainter.kt, demo/src/main/java/com/devbrackets/android/exomediademo/ui/subtitle/SubtitleView.kt, demo/src/main/res/drawable/ic_closed_caption_white_24dp.xml, demo/src/main/res/layout/video_player_activity.xml, demo/src/main/res/values/attrs.xml, demo/src/main/res/values/strings.xml, library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java, library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
Allow for player to reselect default track.
Allow for player to check if renderer type is enabled.
Added Captions example to the sample.
=> Allow tracks to be cleared for a RendererType #666

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java, library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java
- library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java
- library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java
- library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsMobile.java
=> issue#678 Optimize the update for current timestamp

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java
- Plain simple compatibility update
=> Update AudioFocusHelper for Android O and newer

demo/build.gradle, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/activity/FullScreenVideoPlayerActivity.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/FullscreenManager.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/FitsSystemWindowRelativeLayout.kt
- Updates the Demo app setup of fullscreen handling
=> Cleaned up the Fullscreen handling in the Demo app

.editorconfig
=> Added an editorconfig

demo/src/main/kotlin/com/devbrackets/android/exomediademo/data/Samples.kt, demo/src/main/res/layout/audio_player_activity.xml
- Updates the demo app sample media to (mostly) be hosted by devbrackets.com
=> Demo Sample Media Updates

library/src/main/kotlin/com/devbrackets/android/exomedia/core/AnalyticsDelegate.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/ListenerMux.kt
- Created an `AnalyticsDelegate` class to support optional delegates
=> Analytics Delegation

build.gradle
- Updated the Media3 (ExoPlayer) version to `1.0.0-beta02`
=> ExoPlayer Version Update

demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/selection/SelectionScreen.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/video/surface/BaseSurfaceEnvelope.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt
Closes #764 
-  Updated the documentation for `setVideoRotation` to indicate a `TextureView` is required
=> [#764] setVideoRotation documentation

demo/src/main/kotlin/com/devbrackets/android/exomediademo/App.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/util/OkPlayerConfigProvider.kt, demo/src/main/res/layout/video_player_activity.xml
- Updates the demo app to use a single instance of the Okhttp cache
=> Fixed Demo Crash

build.gradle, demo/build.gradle, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/selection/SelectionScreen.kt, library/build.gradle
- Updates the Kotlin version to `1.7.10`
- Updates the Demo Compose version to `1.2.1`
- Updates app compact to `1.5.0`
=> Updated library and demo dependencies

library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/util/Repeater.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/util/StopWatch.kt
Closes #770 
- The buffer amount in the VideoView is now called on the correct thread
=> #770 Fixed Video Buffer Crash

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, build.gradle, demo/build.gradle, demo/src/main/kotlin/com/devbrackets/android/exomediademo/playlist/VideoApi.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/media/VideoPlayerActivity.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/CaptionPopupManager.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/FullscreenManager.kt, library/build.gradle, library/src/main/kotlin/com/devbrackets/android/exomedia/AudioPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/ListenerMux.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/audio/AudioPlayerApi.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/audio/MediaItem.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/listener/ExoPlayerListener.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/video/ExoVideoPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/audio/NativeAudioPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/video/NativeVideoPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/listener/OnVideoSizeChangedListener.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/util/UriExtensions.kt
* Standardized the Audio and Video methods for controlling playback
* Cleaned up old Window references
* Misc. minor updates
=> General Cleanup

build.gradle, demo/build.gradle, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/selection/SelectionActivity.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/DemoNavHost.kt, library/build.gradle
=> Jan 2023 Dependency Updates

build.gradle, demo/build.gradle, library/build.gradle
- Kotlin to `1.8.10`
- Media3 to `1.0.0-rc02`
- Compose Versions (Demo)
=> Updated dependencies

library/src/main/kotlin/com/devbrackets/android/exomedia/AudioPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/ListenerMux.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/listener/ExoPlayerListener.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/source/MediaSourceProvider.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/source/builder/DashMediaSourceBuilder.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/source/builder/DefaultMediaSourceBuilder.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/source/builder/HlsMediaSourceBuilder.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/source/builder/SsMediaSourceBuilder.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/FallbackMediaPlayer.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/FallbackMediaPlayerImpl.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/FallbackTimeline.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/listener/OnTimelineChangedListener.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt
Relates to #783 
- Adds an `OnTimelineChanged` listener to the `VideoView` and `AudioPlayer`
=> Added a listener for Timeline changes

gradle/release/libraryInfo.gradle, libraryInfo.properties
Added publication support for pre-releases and prepared for a `5.0.0-beta01` release
=> `5.0.0-beta01` prep

README.md, library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt
- The `README.md` has been updated for the `5.0.0-beta01` release
=> Updated README.md for `5.0.0-beta01`

build.gradle, demo/build.gradle, gradle/release/publish.gradle, library/build.gradle
- Fixed the gradle build to use java bytecode 1.8 instead of 17, with 17 it would require the implementing apps to target java 17 as well
=> Fixed the gradle build to use java bytecode 1.8 instead of 17

build.gradle, gradle.properties
- Removed the missed (project wide) jetifier flag
- Updated AGP to `8.1.0`
=> Removed Jetifier

README.md, build.gradle, demo/build.gradle, demo/src/main/AndroidManifest.xml, library/build.gradle
- Update Kotlin to `1.9.20`
- Update Media3 to `1.2.0`
- Other demo app version updates
=> Dependency Updates

library/src/main/kotlin/com/devbrackets/android/exomedia/core/renderer/provider/AbstractRenderProvider.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/renderer/provider/AudioRenderProvider.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/renderer/provider/CaptionRenderProvider.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/renderer/provider/MetadataRenderProvider.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/renderer/provider/RenderProvider.kt, library/src/main/kotlin/com/devbrackets/android/exomedia/core/renderer/provider/VideoRenderProvider.kt
- Fixes package imports and constructor args in the `VideoRenderProvider`
- Adds support for the AV1 Video Renderer in the `VideoRenderProvider`
- Updates the RenderProvider instances to share common code
=> VideoRenderProvider Fixes & RenderProvider Improvements

demo/build.gradle, demo/src/main/kotlin/com/devbrackets/android/exomediademo/data/MediaItem.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/playlist/AudioApi.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/playlist/manager/PlaylistManager.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/media/AudioPlayerActivity.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/media/VideoPlayerActivity.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/media/audio/AudioPlayerScreen.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/media/audio/AudioPlayerViewModel.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/selection/SelectionActivity.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/selection/SelectionScreen.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/DemoNavHost.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/Painter.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/ScreenScaffold.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/seek/Seekbar.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/theme/Color.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/theme/Shape.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/theme/Theme.kt, demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/support/compose/theme/Type.kt, gradle/libs.versions.toml
- The Demo Audio Player UI is now built with Jetpack Compose
- Cleaned up the Demo theming
- Update the Demo to use Material3
| Light | Dark |
| ------ | ------ |
| ![audio-player](https://github.com/user-attachments/assets/fbea7dcc-4569-4832-b240-78aefa73b263) | ![audio-player-dark](https://github.com/user-attachments/assets/c7b14091-1909-4a3d-b96f-0e8996f3c4b8) |
=> Updated Demo Audio Player to Compose
