brianwernick/ExoMedia

library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java

Auto-detection fails for some media streams like AAC-HE. For these cases, we can allow the caller to specify a fallback MediaType to use instead of the hardcoded MP3.

Allow the caller to define the default MediaType

---

library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java

for example, the following m3u8 url may fail:
http://pl.youku.com/playlist/m3u8?vid=XMTI5MjIxODIwOA%2525253D%2525253D&keyframe=1&ev=1&ts=1441603988&type=hd2&ep=cSaQG0%2525252BNVccI7SLaiT8bNiWzdnAOXJZ3kmaA%2525252FIgbSMRQMa%2525252FA6DPcqJqwS%2525252Fg%2525253D&token=7057&oip=2021932405&ctype=12&sid=344160398815112a9a271
Using regex may be a relative rude way to recognize the video format, it may fail for some cases still. May be we should use a new way to do it.

fix regex for some m3u8 url cases.

---

library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java

So that people who want a more advanced renderbuilder or some specific format for their usage can also use the EMVideoView implementation without copying it (since overriding is not possible).

Add setVideoURI with RenderBuilder as argument for advanced usage

---

library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/builder/HlsRenderBuilder.java
library/src/main/java/com/devbrackets/android/exomedia/builder/SmoothStreamingRenderBuilder.java

Only added to the VideoView implementation, this should also be usable for the AudioPlayer.
But I only have good test videostreams.

Add RenderBuilder for Smooth Streaming support

---

library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/builder/RenderBuilder.java

https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/extractor/ExtractorSampleSource.html
No extractors needed, just feed it the data and it'll do the work for you. Just like
https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java

Use base ExtractorSampleSource instead of MediaType to detect extractor

---

library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java

This can prevent a memory leak. The Context is being hold on longer than you might think, so it's better to use the Application-context instead.

Fix possible memory leak

---

demo/build.gradle
library/build.gradle
library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/widget/VideoTextureView.java
library/src/main/res/layout/exomedia_exo_view_layout.xml

TextureView was introduced in API 14 as a more performant and reliable successor to SurfaceView. It also behaves as a regular view, which is key for moving/transforming, animations, etc.
Some more info: https://github.com/crosswalk-project/crosswalk-website/wiki/Android-SurfaceView-vs-TextureView

Use TextureView instead of SurfaceView

---

library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java

This was my bad. I thought Surface would clean it up automatically, but wasn't actually exposed until I tried it in a separate project with strict mode enabled

Fix memory leak with the created surface

---

library/src/main/java/com/devbrackets/android/exomedia/core/builder/DashRenderBuilder.java
library/src/main/java/com/devbrackets/android/exomedia/core/builder/HlsRenderBuilder.java
library/src/main/java/com/devbrackets/android/exomedia/core/builder/RenderBuilder.java
library/src/main/java/com/devbrackets/android/exomedia/core/builder/SmoothStreamRenderBuilder.java

This helps with overridding the `HttpDataSource` if it needs to modified (e.g. adding request headers).

Allow the default DataSource to be overridden

---

library/src/main/java/com/devbrackets/android/exomedia/core/api/MediaPlayerApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoMediaPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeMediaPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/NativeVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java

-  Adds a `restart` method that allows the current media playback to be restarted

Added a method to allow restarting media playback

---

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/listener/InternalErrorListener.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/TextureVideoView.java

-  Fixes some javadoc errors (not sure what's going on with `ExoMedia.STATE_IDLE` and why it can't be linked, but whatever)

Fix javadoc errors

---

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java

-  Allows `restart` to be called when `ExoPlayer` is in `ExoPlayer.STATE_IDLE` or `ExoPlayer.STATE_ENDED`

ExoPlayer can be in STATE_ENDED when onCompletion is called

---

library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java

-  Adds an option to not use aspect ratio when measuring the `VideoViewApi`

Add option to not measure ResizingTextureView based on aspect ratio

---

library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/ScaleType.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java

-  Instantiates the `Matrix` for transformations correctly
-  Adds `ScaleType.NONE`
-  Doesn't draw shutters if scale type is `CENTER_CROP`
-  Adds a `getScaleType` method
-  Corrects the matrix multiplication for scaling

Fix underlying scaling issues

---

library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java

Use FIT_CENTER for the default scale

---

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java

-  Adds a flag to `EMExoPlayer` that keeps track of when `stop` is called, and only allows its effects to occur the first time it is called. This flag is cleared at the end of `prepare`. The issue it fixes is that when media finishes playing, `stop` is being called twice. This is a problem when the calls happen in the following scenario:
```java
// media finishes playing
EMExoPlayer.stop(); // sets playWhenReady to false
videoView.setOnCompletionListener(new OnCompletionListener() {
@Override
public void onCompletion() {             
videoView.restart(); // sets playWhenReady to true 
}
});
EMExoPlayer.stop(); // sets playWhenReady to false, and the restart never happens
```

Add a flag that prevents multiple stops

---

library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java

-  Guards against a potential NPE in `ResizingTextureView`

Guard against a potential NPE

---

library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java

-  Fixes a crash on devices below Jellybean due to an incorrect call with a layout listener

Fixes #197

---

library/build.gradle
library/src/androidTest/java/com/devbrackets/android/exomedia/util/MediaSourceUtilTest.java
library/src/main/java/com/devbrackets/android/exomedia/util/MediaSourceUtil.java

`MediaSourceUtil.getExtension(Uri uri)` throws `NullPointerException` for url which ends with `/`.
For example `http://host.com/`

Fix NullPointerException when getting MediaSourceType form an empty path

---

library/src/main/java/com/devbrackets/android/exomedia/core/builder/RenderBuilder.java

- Removed the id3 render from `RenderBuilder` as ExoPlayer only supports it in the HLS format

ID3 Metadata Updates

---

library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java

- Fixes an issue where the `OnSeekCompletionListener` wasn't always correctly informed.
- Updates the VideoControlsLeanback to correctly handle the back button when in loading states

Fixes #338

---

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java

- Removed the set*ImageResource methods in favor of the set*Drawable methods

Removed set*ImageResource methods from the VideoControls

---

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java

This will also update the playback state when attached
and playing.
- Ensure the VideoControls state is preserved when using `VideoView#releaseOnDetachFromWindow = false` and the VideoView is detached and reattached.

Bring progressPollRepeater setup inline with its cleanup

---

library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeVideoDelegate.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java

- Updated the `VideoView` to leave the final frame intact when a video has played to completion

Addresses #413

---

library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java
library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java

- Adds the ability to specify the buffer amounts via `ExoMedia.setLoadControl()`

Addresses Issue #157

---

library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java

- Fixes `onPrepared()` getting called twice in some cases
- Fixes `getDuration()` returning the unknown value when called from `onPrepared()` in some cases

[#444] Fixes onPrepared and getDuration

---

demo/build.gradle
demo/src/main/java/com/devbrackets/android/exomediademo/App.java
library/build.gradle
library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java
library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/MediaSourceBuilder.java

- Deprecated the HttpDataSourceFactoryProvider in favor of the more permissive and aptly named DataSourceFactoryProvider to allow better support for things like cached data sources

Made the DataSourceFactoryProvider more permissive

---

demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/VideoPlayerActivity.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingSurfaceView.java

- Fixed an issue on SDK 21+ causing scaling to not be applied to SurfaceView implementations correctly

[#465] Fixes SurfaceView scaling issues

---

demo/src/main/res/layout/video_player_activity.xml
library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/ScaleType.java
library/src/main/res/values/attributes.xml

- Adds a FIT_XY option to the `ScaleType` enum

[#534] Added a FIT_XY option to the scale type

---

library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/listener/OnVideoSizeChangedListener.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java

- Fix the aspect ratio when the pixel size is not an integer.
> In my project was observed when the video stream had a pixel size of 1x1.3 (approximately). Because of this, the rectangular image became square, since the player thought that the pixel size was 1x1.

Fix aspect ratio

---

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsCore.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java

- Updated the VideoControls to use an interface instead of the abstract class

VideoControls now uses an Interface as the root

---

library/src/main/java/com/devbrackets/android/exomedia/AudioPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/api/AudioPlayerApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java
library/src/main/java/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/audio/NativeAudioPlayer.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoSurfaceVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoTextureVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/exo/ExoVideoDelegate.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeSurfaceVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/core/video/mp/NativeTextureVideoView.java
library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java

- Added `getSelectedTrackIndex` to the `VideoView` and `AudioPlayer`

Added `getSelectedTrackIndex` to the `VideoView` and `AudioPlayer`

---

library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControlsLeanback.java

- Seeking in leanback performs a `hideDelayed()` inside of `onSeekEnded()` in the parent `VideoControls`. However, the controls are never shown before this, so the hide ends up looking like a quick flash followed by the fade out. This change makes it so that prior to seeking the controls are shown as desired.

issue#663: Fix leanback controls show/hide animation during trickplay

---

build.gradle

as in my previous pull requests, updating to 2.9.6 does not include any breaking changes and can "just be done".
Updating gradle is required as it is the new minimum build version required by the current Android Studio version.
I have build the demo with these new settings without any issues, so it should be safe to merge.
- ExoPlayer 2.9.1 -> 2.9.6
- gradle:3.3.0-rc01 -> 3.3.2

Update ExoPlayer to 2.9.6

---

demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/activity/VideoPlayerActivity.kt

- When you are playing video and move your app to background and then resume it then video got stuck, even all controllers were freeze
- I've moved playlistManager.removeVideoApi(videoApi) and  playlistManager.invokeStop() from onStop to onDestroy, so it won't destroy when you are moving app to background

VideoPlayerActivity resume from background fix

---

library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/config/PlayerConfig.kt

Closes #735 
- Playing an item via a Uri now correctly uses the specified `dataSourceFactoryProvider`

[#735] Fixed Uri DataSource creation

---

demo/src/main/kotlin/com/devbrackets/android/exomediademo/playlist/AudioApi.kt
demo/src/main/kotlin/com/devbrackets/android/exomediademo/playlist/BaseMediaApi.kt
demo/src/main/kotlin/com/devbrackets/android/exomediademo/playlist/VideoApi.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/AudioPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/ListenerMux.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/audio/AudioPlayerApi.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/video/ExoVideoPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/FallbackMediaPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/FallbackMediaPlayerImpl.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/audio/NativeAudioPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/video/NativeVideoPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/util/FallbackManager.kt

- Created a `FallbackMediaPlayer` that handles the "native" fallback media playback using the system `MediaPlayer`. This standardization better allows us to track the playback state (useful for #257) and keep the handling consistent between the Video and Audio players

Fallback Media Player standardization

---

demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/media/VideoPlayerActivity.kt
demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/selection/SelectionScreen.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/AudioPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/ListenerMux.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/listener/ExoPlayerListener.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/state/PlaybackState.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/state/PlaybackStateListener.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/FallbackMediaPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/FallbackMediaPlayerImpl.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/manager/StateStore.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt

Closes #257 
- Added a consistent playback state between the Audio and Video playback for both the ExoPlayer and "Native" (Fallback) media players.
- Added a listener for playback state changes

#257 Playback State Callback

---

library/src/main/kotlin/com/devbrackets/android/exomedia/listener/OnPreparedListener.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt

Closes #732 
- The `ExoMediaPlayerImpl` now properly instantiates the backing Exo Player on initialization

[#732] Fixed Null Pointer Crash

---

library/src/main/kotlin/com/devbrackets/android/exomedia/AudioPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/audio/AudioPlayerApi.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/audio/ExoAudioPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/core/video/ExoVideoPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/audio/NativeAudioPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/fallback/video/NativeVideoPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayer.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/ExoMediaPlayerImpl.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/nmp/manager/track/TrackManager.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/unified/AudioPlayerWrapper.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/unified/VideoViewWrapper.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/unified/ext/PlayerExt.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/util/FallbackManager.kt

- Adds a `AudioPlayerWrapper` to expose the `AudioPlayer` to the Media3 framework. This can be manually constructed or through the `.asMedia3Player()` extension on the `AudioPlayer`
- Adds a `VideoViewWrapper` to expose the `VideoView` to the Media3 framework. This can be manually constructed or through the `.asMedia3Player()` extension on the `VideoView`

Media3 Wrappers

---

build.gradle
demo/src/main/kotlin/com/devbrackets/android/exomediademo/data/Samples.kt
demo/src/main/kotlin/com/devbrackets/android/exomediademo/util/OkHttpDataSourceFactoryProvider.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/VideoView.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsMobile.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsTv.kt
library/src/main/res/values/strings.xml

Closes #488
- Media3 dependencies have been updated to the `1.0.0` release
- The `DefaultVideoControls` and children now represent Live/Event/VoD streams appropriately
- Video manifest files are now excluded from the file cache in the *demo* app

[#488] Improves handling of Live/Event streams

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build-and-test.yml
.github/workflows/release.yml
build.gradle
demo/build.gradle
gradle.properties
gradle/util/testOutput.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle

- AGP to `8.0.1` (was `7.4.2`)
- Kotlin to `1.8.21` (was `1.8.10`)
- Moves the test result output to a separate gradle file
- Demo dependencies

May 2023 Dependency Updates

---

demo/build.gradle
demo/gradle.properties

Addresses #795 
- Updated the Demo to use the AndroidX ConstraintLayout 
- Disabled Jettifier

[#795] Updated Demo Support Libs

---

library/src/main/kotlin/com/devbrackets/android/exomedia/core/renderer/provider/AudioRenderProvider.kt

it was broken. Class names and constructor usage were not matching the current media3 implementation

Fix AudioRenderProvider.kt

---

library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsMobile.kt
library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsTv.kt

Addresses #810
- The `DefaultVideoControls` implementations to retain view removal state
- Changed how `enabled` and `removed` was tracked to be easier to understand / maintain

Issue-810: Fixed VideoControls Removals
